name: Test Changed File Detection

on:
  push:
    branches:
      - master

jobs:
  detect-and-prepare:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Detect changed files (safe)
      id: detect
      run: |
        echo "Recent commits:"
        git log -2 --oneline || echo "Only one commit found"

        # Check how many commits exist
        COMMIT_COUNT=$(git rev-list --count HEAD)
        echo "Commit count: $COMMIT_COUNT"

        if [ "$COMMIT_COUNT" -eq 1 ]; then
          echo "First commit detected. Listing all files."
          git ls-files > changed_files.txt
        else
          echo "Using git diff to get changed files"
          git diff --name-only HEAD^ HEAD > changed_files.txt
        fi

        echo "Changed files:"
        cat changed_files.txt

        echo "FILES<<EOF" >> $GITHUB_ENV
        cat changed_files.txt >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV

    - name: Copy only changed files to deploy folder
      run: |
        mkdir -p deploy
        while IFS= read -r file; do
          echo "Copying $file"
          if [[ -f "$file" ]]; then
            mkdir -p "deploy/$(dirname "$file")"
            cp "$file" "deploy/$file"
          fi
        done < changed_files.txt

    - name: Show deploy folder content
      run: |
        echo "Deployed files:"
        find deploy/ || echo "No files to deploy"

    - name: Upload deploy folder as artifact
      uses: actions/upload-artifact@v4
      with:
        name: deploy-folder
        path: deploy/
